name: Deploy na VM GCP - container Python Runner

on:
  push:
    branches:
      - main

env:
  API_KEY: ${{ secrets.API_KEY }} # DEFINA SUA API KEY AQUI, ELA VAI SER USADA PARA AUTENTICAR AS REQUISIÇÕES AO SERVIÇO PYTHON

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Executar comandos via SSH na VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.GCP_VM_HOST }}
          username: ${{ secrets.GCP_VM_USER }}
          key: ${{ secrets.GCP_SSH_KEY }}
          envs: API_KEY # EXPORTA A VARIÁVEL DE AMBIENTE PARA O COMANDO SSH         
          script: |
            # Exporte a variável para que o Docker Compose consiga visualizá-la
            export API_KEY=$API_KEY 

            echo "Entrando no diretório do projeto"
            cd ~/n8n_data

            echo "Atualizando código"
            git pull # PARA QUE ISSO FUNCIONE, SEM QUESTIONAMENTOS, O REPOSITÓRIO PRECISA
                     # ESTAR CONFIGURADO COM git config pull.rebase false. GARANTE MERGE PADRÃO EM VEZ DE REBASE 

            echo "Parando container"
            docker compose down python_runner

            echo "Removendo imagem antiga"
            docker image rm -f n8n_data-python_runner || true

            echo "Subindo container atualizado"
            docker compose up -d python_runner

            echo "Deploy finalizado com sucesso"
