# Use uma imagem Python oficial e leve como base
FROM n8nio/n8n:latest

# Defina o diretório de trabalho dentro do contêiner
WORKDIR /home/node/.n8n

ARG GENERIC_TIMEZONE
ENV GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
ARG N8N_HOST
ENV N8N_HOST=${N8N_HOST}
ARG N8N_PROTOCOL=${N8N_PROTOCOL}
ENV N8N_PROTOCOL=${N8N_PROTOCOL}
ARG WEBHOOK_URL
ENV WEBHOOK_URL=${WEBHOOK_URL}
ARG N8N_PORT
ENV N8N_PORT=${N8N_PORT}

# POSTGRESQL ENV VARIABLES
ARG DB_TYPE
ENV DB_TYPE=${DB_TYPE}
ARG DB_POSTGRESDB_HOST
ENV DB_POSTGRESDB_HOST=${DB_POSTGRESDB_HOST}
ARG DB_POSTGRESDB_PORT
ENV DB_POSTGRESDB_PORT=${DB_POSTGRESDB_PORT}
ARG DB_POSTGRESDB_NAME
ENV DB_POSTGRESDB_NAME=${DB_POSTGRESDB_NAME}
ARG DB_POSTGRESDB_USER
ENV DB_POSTGRESDB_USER=${DB_POSTGRESDB_USER}
ARG DB_POSTGRESDB_PASSWORD
ENV DB_POSTGRESDB_PASSWORD=${DB_POSTGRESDB_PASSWORD}
ARG N8N_ENCRYPTION_KEY
ENV N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}

EXPOSE ${N8N_PORT}