# Use uma imagem Python oficial e leve como base
FROM n8nio/n8n:latest

# Defina o diretório de trabalho dentro do contêiner
WORKDIR /home/node/.n8n

ARG GENERIC_TIMEZONE
ENV GENERIC_TIMEZONE=${GENERIC_TIMEZONE} --
ARG N8N_HOST
ENV N8N_HOST=${N8N_HOST}
ARG N8N_PROTOCOL=${N8N_PROTOCOL}
ENV N8N_PROTOCOL=${N8N_PROTOCOL}
ARG WEBHOOK_URL
ENV WEBHOOK_URL=${WEBHOOK_URL}
ARG N8N_PORT
ENV N8N_PORT=${N8N_PORT}

EXPOSE ${N8N_PORT}