name: Docker Image & Cloud Run Deploy N8N
#
on:
  push:
    branches: [ "main" ]
    paths: 
      - '.github/workflows/n8n.yml'        

env:
  PROJECT_ID: n8n-meus-ensinamentos   # Substitua pelo ID do seu projeto no GCP 
  PORT: 5678                          # Porta padrão do n8n                                     
  REGION: us-central1                 # Região do GCP (ex: São Paulo ou us-central1)
  SERVICE_NAME: n8n                   # Nome que o serviço terá no Cloud Run
  REPO_NAME: n8n                      # Nome do seu repositório no Artifact Registry. Deve ser criado previamente no GCP.
  
  # N8N ENV VARIABLES
  GENERIC_TIMEZONE: America/Sao_Paulo
  N8N_HOST: n8n-574973424283.us-central1.run.app
  #N8N_HOST: antoniodantasn8n.ddns.net
  N8N_PROTOCOL: https
  N8N_TRUST_PROXY: true # Habilita a confiança em proxies reversos, o que é importante para o correto funcionamento do n8n quando implantado em ambientes como o Cloud Run, 
                        # que atuam como proxies reversos.
  WEBHOOK_URL: https://n8n-574973424283.us-central1.run.app # CONFIGURADO NO NOIP  
  N8N_ENCRYPTION_KEY: ${{ secrets.N8N_ENCRYPTION_KEY }} # Crie esse Secret no GitHub com uma chave de criptografia segura (pode ser gerada usando `openssl rand -base64 32`)
  
  # POSTGRES ENV VARIABLES
  DB_TYPE: postgresdb
  DB_POSTGRESDB_HOST: 34.42.180.102
  #DB_POSTGRESDB_HOST: /cloudsql/n8n-meus-ensinamentos:us-central1:postgres-cloudsql
  DB_POSTGRESDB_PORT: 5432
  DB_POSTGRESDB_DATABASE: n8n
  DB_POSTGRESDB_USER: n8n
  DB_POSTGRESDB_PASSWORD: ${{ secrets.DB_POSTGRESDB_PASSWORD }} # Crie esse Secret no GitHub com a senha do seu banco de dados Postgres
  DB_POSTGRESDB_CONNECTION_TIMEOUT: 60000
  DB_POSTGRESDB_SCHEMA: public
  DB_POSTGRESDB_SSL_ENABLED: true # Configuração para SSL, ajuste conforme necessário. Se estiver usando o Cloud SQL, geralmente não é necessário habilitar SSL.
  DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED: false # Configuração para aceitar certificados autoassinados, caso esteja usando SSL. Ajuste conforme necessário.


jobs:

  deploy:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Autenticar no Google Cloud via Service Account
      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }} # Crie esse Secret no GitHub com o JSON da sua Service Account

      # 2. Configurar o gcloud CLI no runner
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      # 3. Autenticar o Docker para conseguir dar Push no Artifact Registry do GCP
      - name: Configure Docker for GCP
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      # 4. Build e Push da imagem Docker para o Artifact Registry do GCP
      #
      # NÃO EXECUTA MAIS COMANDOS NA MÁQUINA VIRTUAL, APENAS FAZ O BUILD E PUSH DA IMAGEM PARA O REGISTRY. 
      - name: Build and Push the Docker image to Artifact Registry
        run: |
          
          # O padrão do Artifact Registry é: REGIAO-docker.pkg.dev/PROJECT_ID/REPO_NAME/IMAGE_NAME:TAG
          IMAGE_ID="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}"
          
          #TAG=$(date +%Y%m%d%H%M%S)
          TAG=latest
          
          docker build -t $IMAGE_ID:$TAG . # PEGA O DOCKERFILE AQUI

          docker push $IMAGE_ID:$TAG 

      # 5. Deploy da imagem Docker para o Cloud Run
      #
      # --add-cloudsql-instances: Adiciona a instância do Cloud SQL para que o Cloud Run possa se conectar ao banco de dados Postgres hospedado no Cloud SQL. 
      # Substitua "postgres-cloudsql" pelo nome da sua instância do Cloud SQL.
      # 5. Deploy da imagem Docker para o Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --port=${{ env.PORT }} \
            --image="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:latest" \
            --region=${{ env.REGION }} \
            --platform=managed \
            --allow-unauthenticated \
            --memory=2Gi \
            --min-instances=1 \
            --timeout=300 \
            --set-env-vars=DB_TYPE=${{ env.DB_TYPE }} \
            --set-env-vars=N8N_ENCRYPTION_KEY='${{ secrets.N8N_ENCRYPTION_KEY }}' \
            --set-env-vars=DB_POSTGRESDB_SCHEMA=${{ env.DB_POSTGRESDB_SCHEMA }} \
            --set-env-vars=DB_POSTGRESDB_SSL_ENABLED=${{ env.DB_POSTGRESDB_SSL_ENABLED }} \
            --set-env-vars=DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED=${{ env.DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED }} \
            --set-env-vars=DB_POSTGRESDB_CONNECTION_TIMEOUT=${{ env.DB_POSTGRESDB_CONNECTION_TIMEOUT }} \
            --set-env-vars=N8N_TRUST_PROXY=${{ env.N8N_TRUST_PROXY }} \
            --set-env-vars=GENERIC_TIMEZONE=${{ env.GENERIC_TIMEZONE }} \
            --set-env-vars=N8N_HOST=${{ env.N8N_HOST }} \
            --set-env-vars=N8N_PROTOCOL=${{ env.N8N_PROTOCOL }} \
            --set-env-vars=WEBHOOK_URL=${{ env.WEBHOOK_URL }} \
            --set-env-vars=DB_POSTGRESDB_HOST=${{ env.DB_POSTGRESDB_HOST }} \
            --set-env-vars=DB_POSTGRESDB_PORT=${{ env.DB_POSTGRESDB_PORT }} \
            --set-env-vars=DB_POSTGRESDB_DATABASE=${{ env.DB_POSTGRESDB_DATABASE }} \
            --set-env-vars=DB_POSTGRESDB_USER=${{ env.DB_POSTGRESDB_USER }} \
            --set-env-vars=DB_POSTGRESDB_PASSWORD='${{ secrets.DB_POSTGRESDB_PASSWORD }}'